server:
  port: 0

logging:
  file:
    name: logs/notification-service.log
    max-size: 10Mb
    max-history: 7

  level.org.hibernate:
    SQL: debug
    type.descriptor.sql: trace

management:
  endpoints:
    web.exposure.include: "*"
    health.show-details: always

spring:
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER:http://localhost:5555/}

  jackson:
    default-property-inclusion: NON_NULL

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register-health-check: false
        instance-id: "${spring.cloud.client.hostname}_${spring.application.name}:${random.value}"

  mail:
    host: smtp.gmail.com
    port: 587
    username: algotrade.platform.pro@gmail.com
    password: wbpnkugywirhmmtf

  # Other properties
    properties:
      mail:
        smtp:
          auth: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
          # TLS , port 587
          starttls:
            enable: true
#            required: true
          # SSL, post 465
#         socketFactory.port: 465
#         socketFactory.class: javax.net.ssl.SSLSocketFactory
