server:
  port: 0

logging:
  file:
    name: logs/person-service.log
    max-size: 10Mb
    max-history: 7

  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace

management:
  endpoints:
    web.exposure.include: "*"
    health.show-details: always

spring:
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER:http://localhost:5555/}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    default-property-inclusion: NON_NULL

  cloud:
    consul:
      host: localhost
      port: 8500

      discovery:
        register-health-check: false
        instance-id: "${spring.cloud.client.hostname}_${spring.application.name}:${random.value}"

  datasource:
    url: jdbc:mysql://localhost:3306/persons_schema
    username: springuser
    password: The_Password
    driver-class-name: com.mysql.cj.jdbc.Driver